### ISSUE TITLE
LIMS work for new Feature Extraction and Inference workflow step

### ISSUE THREAD

**Issue by isaak-willett** [AllenInstitute/croissant#37]
# Overview:
Introducing a new workflow step for Feature Extraction and Classification requires changes to the LIMS strategies, job transitions, and updates to LIMS tables to integrate with the existing pieces of the Ophys Segmentation Pipeline.

# Tasks:
- [ ] Create a new LIMS strategy for running the Feature Extraction and Inference Workflow Step
- [ ] Create new LIMS job queue record in the database (LIMS datafix script)
- [ ] Create new LIMS executable record in the database(LIMS datafix script)
- [ ] Add new columns to LIMS ophys_cell_segmentation_runs table (db migration script). @isaak-willett What new columns?
- [ ] Update the LIMS "roi_exclusion_labels" table. @isaak-willett I don't see this table in LIMS. Please clarify.

# Acceptance Criteria:
- [ ] On a test LIMS server LIMS successfully transitions from Ophys_extract_traces workflow step to Feature_extraction_and_inference workflow step, executes all steps in Feature_Extraction_and_Inference workflow step successfully, and writes the ROIs to LIMs with the correct exclusion labels.

**Comment by isaak-willett** [comment]
I'm closing this issue as the work for this is now associated with `ophys_etl`
