### ISSUE TITLE
~Containerize Croissant Croissant and MlFlow~

### ISSUE THREAD

**Issue by isaak-willett** [AllenInstitute/croissant#38]
# Dan comment:
I don't think we need this container. Currently we have a container that contains `ophys_etl_pipelines`. We should add a transform step to `ophys_etl_pipelines` that performs Feature Extraction and inference. It will have `croissant` as a dependency. Once done, the current container will automatically contain the `croissant` functionality. `ophys_etl_pipeline` could just have an argchema entry point that drives `croissant` feature extraction and inference.

# Overview:
Croissant contains all necessary code for generating features for ROIs coming through the pipeline. MlFlow contains the resources to pull a model from the model registry (as yet undecided how to get model to pipeline). These two resources need to be containerized to run in the pipeline.

# Tasks:
- [ ] Create Singularity container recipe containing both Croissant and MlFlow
- [ ] Create custom runscript in Singularity container that given input json defined in [design document](http://confluence.corp.alleninstitute.org/display/IT/DRAFT%3A+2020+Ophys+Segmentation+Refactor+and+Update) (see section Feature Extraction and Inference) extracts features and classifies ROIs using trained model. This produces an output json that the LIMs strategy operating the module is capable of ingesting see [design document](http://confluence.corp.alleninstitute.org/display/IT/DRAFT%3A+2020+Ophys+Segmentation+Refactor+and+Update) (see section Feature Extraction and Classification)
- [ ] Upload container to sylabs cloud

# Acceptance Criteria:
- [ ] Container exists on sylabs lab having been built with good practices
- [ ] Run script in container creates output.json expected given expected input.json

**Comment by isaak-willett** [comment]
I agree with Dan's comment I'm going to close this issue in favor of keeping croissant as a dependency in ophys_etl
